CREATE PROCEDURE ListarCorresponsales
AS

BEGIN
	SET NOCOUNT ON;

	SELECT
		C.COR_CORRESPONSAL_ID,
		C.COR_NOMBRE + ' - ' + CONVERT(VARCHAR(MAX),COUNT(CO.CONTEO)) AS CONT_OFICINA 
	FROM 
		(SELECT
		O.OFI_CORRESPONSAL_ID,
		COUNT(O.OFI_NOMBRE) AS CONTEO 
     FROM
		OFICINAS  O
     GROUP BY
		O.OFI_CORRESPONSAL_ID, O.OFI_NOMBRE) AS CO
	INNER JOIN
		CORRESPONSALES C
	ON
		C.COR_CORRESPONSAL_ID = CO.OFI_CORRESPONSAL_ID
	GROUP BY
		C.COR_CORRESPONSAL_ID, C.COR_NOMBRE, CO.CONTEO;

	SET NOCOUNT OFF;
END

